Feature/OPDLG 330  Dynamic attributes
opendialogai/opendialog pull request #233
Opened 2021-01-26 14:32 UTC by bendeeson

Adds the ability to create 'dynamic attributes' that are stored in the database rather than config files.

Depends on this PR for core: https://github.com/opendialogai/core/pull/428

Adds new `/admin/api/dynamic-attribute` api resource with support for CRUD of DynamicAttribute model. 
Adds new `/admin/api/dynamic-attributes/{upload,download}` (note the s) routes for uploading/downloading all dynamic-attributes as JSON. 

See app/Http/Controllers/API/DynamicAttributesController.php

2021-01-26 14:38 UTC, bendeeson commented on routes/api.php
> +        Route::get('dynamic-attributes/download', 'DynamicAttributesController@download');
Note that this route is `dynamic-attributes` with an s. Avoids overloading the `dynamic-attribute/download` route with two meanings (download Dynamic-attributes/Get the dynamic attribute with id 'download')

2021-01-27 15:54 UTC, elliotmassen commented on app/Http/Controllers/API/DynamicAttributesController.php
> +            ['Content-Disposition' => 'attachment; filename="dynamic-attributes.json"']
I'm thinking the filename should be `custom-attributes.json`.

2021-01-27 16:00 UTC, elliotmassen requested changes
This looks great! 🔥  Just a few comments and the following:

 - [ ] Would you be able to commit the Composer file updates to use the related `opendialogai/core` dependency? Ie. to update it to be `dev-feature/OPNDLG-330--dynamic-attributes-crud`. We'll need to change it again before merging, but just keeps it related and makes it easier to pull and test before approving.
 - [ ] Could you add some endpoint tests similar to what we do in `ConversationsTest`?

2021-02-02 10:38 UTC, elliotmassen commented on composer.json
> +        "opendialogai/core": "dev-feature/OPNDLG-330--dynamic-attributes-crud",
Just leaving this comment to remind us to merge the core changes prior to this work and to update this depedency to the latest `1.x` afterwards.

2021-02-02 10:38 UTC, elliotmassen approved these changes

2021-02-02 10:39 UTC, elliotmassen commented
Thanks for making the changes - the tests look great :)

2021-02-03 11:46 UTC, elliotmassen commented
Closing in favour of #237.

2021-02-03 11:46 UTC, closed without merging