Feature/opndlg 344  integrate dynamic attributes with attribute engine
opendialogai/opendialog pull request #237
Opened 2021-02-02 18:41 UTC by bendeeson

Introduces CRUD endpoints for the new DynamicAttributes model (See https://github.com/opendialogai/core/pull/433).
Adds new /admin/api/dynamic-attribute api resource with support for CRUD of DynamicAttribute model.
Adds new /admin/api/dynamic-attributes/{upload,download} (note the s) routes for uploading/downloading all dynamic-attributes as JSON.

Adds new dynamic-attributes:import and dynamic-attributes:export artisan commands for exporting the dynamic-attributes to a .json file.

2021-02-03 11:52 UTC, elliotmassen commented on composer.json
> +        "opendialogai/core": "dev-feature/OPNDLG-344--integrate-dynamic-attributes-with-attribute-engine",
Just leaving this as a reminder to update to `1.x-dev` after opendialogai/core#433 is merged.

2021-02-03 14:04 UTC, elliotmassen requested changes
This is really great work! Good call on leaning on the existing `ImportExportHelper` concept. The tests are nice and extensive too! Please see the items below and some comments on specific lines.

- [ ] `import --delete-existing` shouldn't give the "Some ids are already in use" error, as it should be deleting the existing ones prior to importing. It would be worth adding a test in for this possibility.
- [ ] After using this locally, I think it'll make more sense to refer to these commands as `custom-attributes:*` rather than `dynamic-attributes:*` as this fits in better to the new "tiers" of components we seem to be relying on (ie. "core", "app" & "custom"). If you could also update the messaging in the log statements to reflect this too that'd be great.

2021-02-08 08:28 UTC, bendeeson commented on database/factories/DynamicAttributeFactory.php
> +        'attribute_type' => $faker->regexify(AttributeResolver::getValidTypePattern())
That makes sense. I've updated the factory to select from a list of known good ids.

2021-02-08 08:37 UTC, bendeeson commented on app/Console/Commands/Specification/ImportDynamicAttributes.php
> +                $this->error(json_encode($error, JSON_PRETTY_PRINT));
This has been updated to improve the display of the error message for the `artisan custom-attributes:import` command. 
It has not been updated with a `--delete-existing` prompt however as this would require a significant refactor of the error handling and leave error handling in the attribute engine inconsistent with other engines.

2021-02-08 19:06 UTC, elliotmassen approved these changes
This ready to merge once opendialogai/core#433 is merged, which will likely happen after opendialogai/core#435 is merged. To whoever does merge this PR: please remember to update the composer dependency for core before merging :)

2021-02-15 17:52 UTC, elliotmassen commented
opendialogai/core#433 is now merged, but I'll need to wait until the `1.x` branch here is updated to Laravel 8, as I can't update the core dependency until the conflict is resolved:

![Screenshot 2021-02-15 at 17 52 14](https://user-images.githubusercontent.com/6834105/107979486-8a4d8800-6fb6-11eb-85b3-6d0d7944d286.png)

2021-02-17 18:08 UTC, merged