Implementation for File Upload handling on OpenDialog
opendialogai/opendialog pull request #433
Opened 2022-01-04 09:19 UTC by aniekanoffiong

This Pull Request provides implementation for File Uploads in Open Dialog. It utilizes Laravel's File Upload functionality and provides some config values for configurations like minimum and maximum file upload size.

2022-01-04 14:09 UTC, stu-greenshoots commented on app/Http/Controllers/FileUploadController.php
> +        $fileToUpload = $request->file('image');
A more generic parameter name would be better here, since this could be for files other than images

2022-01-04 14:10 UTC, stu-greenshoots commented on app/Services/FileUploadClient.php
> +class FileUploadClient implements FileUploadInterface
Perhaps this could be named something like 'LocalFileUpload'Client or similar to go with an `S3FileUploadClient`

2022-01-04 14:14 UTC, stu-greenshoots commented on app/Http/Controllers/FileUploadController.php
> +        $storagePath = '/uploads';
The ticket mentions `Rename all files upon upload`  - have you accounted for this anywhere?

2022-01-06 17:33 UTC, stu-greenshoots requested changes
I've added a couple of comments to look through here as well as in the core PR. For this PR can you update composer to pull in the dependency and add some tests for file uploading?

I'm wondering also how this will work with tenants - have you tried this? We will need to make sure that each tenant has it's own space to store files

2022-01-06 17:33 UTC, stu-greenshoots commented on app/Http/Controllers/FileUploadController.php
> +        $storagePath = '/uploads';
I have mentioned this in the core PR - I think if we can centralise the renaming, that would be best

2022-01-06 17:33 UTC, stu-greenshoots commented on app/Http/Controllers/FileUploadController.php
> +            'path' => $path,
Is this path returned accessible? EG if this was an image, could it be loaded in the browser?

2022-01-06 17:33 UTC, stu-greenshoots commented on app/Http/Requests/AudioFileUploadRequest.php
> +<?php
I think the request classes can be moved into the same place in core, or this one can be moved to the voice package when needed

2022-01-12 11:58 UTC, stu-greenshoots approved these changes
This is looking good and working as expected. I am happy to approve and merge.

@patshone-gsl - whether the file is uploaded to the local disk or S3 is handled by setting the ENABLE_S3_FILE_UPLOAD env. I have tested both, and happy that they work

2022-01-12 11:59 UTC, stu-greenshoots commented
@aniekanoffiong - could you update the composer dependency here please

2022-01-19 17:40 UTC, patshone-gsl approved these changes

2022-01-19 17:40 UTC, merged