Ports the code from saas about intents/messages ordering bug.
opendialogai/opendialog pull request #488
Opened 2022-07-08 09:47 UTC by goranambar

This fixes the intents/messages ordering bug. It should be used with [this core branch](https://github.com/opendialogai/core/pull/647).

2022-07-12 17:23 UTC, elliotmassen requested changes
Thanks for this Goran - I haven't had chance to test this locally unfortunately, but looking at the code it looks as I'd expect. One small thing is that I think we'll want to keep the uses of `prepareODHeaders` here.

2022-07-13 08:27 UTC, goranambar commented
> One small thing is that I think we'll want to keep the uses of `prepareODHeaders` here.

Not sure how this came to be?! It was from merged DGraph migration branch. Maybe I messed up something. I fixed it now.

2022-07-15 10:40 UTC, elliotmassen commented on composer.json
> +        "opendialogai/core": "dev-bug/OPNDLG-1516_intents_messages_ordering",
Just leaving myself a reminder that this will be need to be updated once https://github.com/opendialogai/core/pull/647 is merged..

2022-07-15 10:40 UTC, elliotmassen approved these changes

2022-07-15 11:08 UTC, merged